# Generated by Django 6.0.7 on 2026-07-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
